### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by AJenbo**
Here are the latest changes from upstream, including the changes to the engine code for reducing the need for byte swapping :) Once this is merged I can start going over the changes, cleaning up the history and picking individual parts for merging.

### CODE REVIEW

**Comment by arczi84** [comment]
nice , one thing, shouldn't libpthreds be called libpthread ?

**Comment by AJenbo** [comment]
@arczi84 I'm not sure what you are referring to regarding the naming?

**Comment by arczi84** [comment]
I have error  can't find -lpthread**s**
I have -lpthread here without 's'.
Didn't have that error earlier.

**Comment by AJenbo** [comment]
Really not sure what that could be related to, have you tried rerunning the CMake script from a clean folder? You will have to debug it since I'm not having this issue on any of my Linux systems (Windows and Mac builds also pass).

**Comment by arczi84** [comment]
OK, I will.

**Pull request merged**
